<a href="https://colab.research.google.com/github/AdicherlaVenkataSai/InternshalaML/blob/master/Ensemble_modelling_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ensemble models: considering various predictions and making a final prediction

max voting :categorical
       
average with some weights
(good perf - more wt
poor perf - less wt) :continuous

voting

averaging

wt averaging

ranking averaging

# max voting

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('data_cleaned.csv')
data.shape

(891, 25)

In [0]:
x = data.drop(['Survived'], axis = 1)
y = data['Survived']

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x, y,  random_state = 10, stratify =y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((668, 24), (223, 24), (668,), (223,))

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [0]:
model1 = LogisticRegression()
model1.fit(x_train, y_train)
predict1= model1.predict(x_test)
predict1[:10], model1.score(x_test, y_test)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


(array([1, 0, 0, 0, 0, 1, 1, 0, 0, 1]), 0.8251121076233184)

In [0]:
model2 = KNeighborsClassifier(n_neighbors = 5)
model2.fit(x_train, y_train)
predict2= model2.predict(x_test)
predict2[:10], model2.score(x_test, y_test)

(array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1]), 0.7354260089686099)

In [0]:
model3 = DecisionTreeClassifier(max_depth = 7)
model3.fit(x_train, y_train)
predict3= model3.predict(x_test)
predict3[:10], model3.score(x_test, y_test)

(array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1]), 0.8430493273542601)

In [0]:
# importing

from statistics import mode
final_pred = np.array([])
for i in range(len(x_test)):
  final_pred = np.append(final_pred, mode([predict1[i], predict2[i], predict3[i]]))
  

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, final_pred)

0.8430493273542601

In [0]:
accuracy_score(y_test, predict1), accuracy_score(y_test, predict2), accuracy_score(y_test, predict3)

(0.8251121076233184, 0.7354260089686099, 0.8430493273542601)

# averaging

In [0]:
data1 = pd.read_csv('train_cleaned.csv')

In [0]:
x = data1.drop(['Item_Outlet_Sales'], axis = 1)
y = data1['Item_Outlet_Sales']

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x, y,  random_state = 10)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((6392, 45), (2131, 45), (6392,), (2131,))

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [0]:
model1 = LinearRegression()
model1.fit(x_train, y_train)
predict1= model1.predict(x_test)
predict1[:10], model1.score(x_test, y_test)


(array([4113.07071883, 1748.2066241 , 2960.07626156, 1396.51926868,
        3008.23091903, 2734.92728319, 1919.60560968, 2998.1415517 ,
        2690.21085839, 1219.3775823 ]), 0.5615846417150259)

In [0]:
model2 = KNeighborsRegressor(n_neighbors = 5)
model2.fit(x_train, y_train)
predict2= model2.predict(x_test)
predict2[:10], model2.score(x_test, y_test)

(array([4966.06904, 2246.54236, 2632.04056, 1651.58348, 3198.90268,
        3600.91272, 2081.9566 , 3869.36328, 1957.05252, 1232.52896]),
 0.48251889265968373)

In [0]:
model3 = DecisionTreeRegressor(max_depth = 7)
model3.fit(x_train, y_train)
predict3= model3.predict(x_test)
predict3[:10], model3.score(x_test, y_test)

(array([4131.61181212, 1683.12362744, 3129.04552991, 1399.21807527,
        3006.31911376, 3129.04552991, 1683.12362744, 3129.04552991,
        3129.04552991, 1276.8294141 ]), 0.5628062355547123)

In [0]:

from statistics import mean
final_pred = np.array([])
for i in range(len(x_test)):
  final_pred = np.append(final_pred, mean([predict1[i], predict2[i], predict3[i]]))

In [0]:
from sklearn.metrics import r2_score
r2_score(y_test, final_pred)

0.5725830779245229

In [0]:
r2_score(y_test, predict1), r2_score(y_test, predict2), r2_score(y_test, predict3)

(0.5615846417150259, 0.48251889265968373, 0.5628062355547123)

# weighted averaging

In [0]:

from statistics import mean
final_pred = np.array([])
for i in range(len(x_test)):
  final_pred = np.append(final_pred, mean([predict1[i], predict1[i], predict2[i],predict3[i], predict3[i]]))

In [0]:
r2_score(y_test, final_pred)

0.5785226099661214

there is a slight change in the r2

# rank averaging

In [0]:
m1_score = model1.score(x_test, y_test)
m2_score = model2.score(x_test, y_test)
m3_score = model3.score(x_test, y_test)
m1_score, m2_score, m3_score

(0.5615846417150259, 0.48251889265968373, 0.5628062355547123)

In [0]:
index = [1, 2, 3]
test_r2 =[m1_score, m2_score, m3_score]

rank_eval = pd.DataFrame({'score':test_r2}, index = index)
rank_eval

score
1  0.561585
2  0.482519
3  0.562806

In [0]:
# order them

sorted_rank = rank_eval.sort_values('score')
sorted_rank

sorted_rank['rank']= [i for i in range(1,4)]
sorted_rank

score  rank
2  0.482519     1
1  0.561585     2
3  0.562806     3

In [0]:
sorted_rank['weight'] = sorted_rank['rank'] / sorted_rank['rank'].sum()
sorted_rank

score  rank    weight
2  0.482519     1  0.166667
1  0.561585     2  0.333333
3  0.562806     3  0.500000

In [0]:
wt_pred1 = predict1 * float(sorted_rank.loc[[1], ['weight']].values)
wt_pred2 = predict2 * float(sorted_rank.loc[[2], ['weight']].values)
wt_pred3 = predict3 * float(sorted_rank.loc[[3], ['weight']].values)

ranked_prediction = wt_pred1 + wt_pred2 + wt_pred3
ranked_prediction

array([4264.50765234, 1798.72108176, 2989.88827881, ..., 2774.30644221,
        788.46445262, 4248.00193214])

In [0]:
r2_score(y_test, ranked_prediction)

0.5786055135143513

the performane is slightly imporved

advantages:


*   captures multiple signals
*   brings in diversity
*   reduces overfitting
*   proved toperform execeptionally well in data science competitions



dis advantages:


*   high complexity
*   Lacks interpretability
*   time consuming
*   more computations









